# Generated by Django 4.2.5 on 2023-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='needs_reset_email',
        ),
    ]
